-- Projeto:  Tupi
INSERT INTO public.projects (id, name, tagline, icon, color, soft, description, objectives, metrics, tech, team, trilha)
VALUES ('tupi', 'Tupi', 'Maquininha e ecossistema de pagamentos para lojistas', 'credit-card', '#2754C5', '#EAF0FD', 'Solução de maquininha de cartão (POS) e gestão de recebíveis voltada a pequenos e médios lojistas, com foco em simplicidade na adesão e antecipação de recebíveis.', '["Diminuir o tempo de ativação de uma nova maquininha para menos de 10 minutos","Aumentar a adesão à antecipação automática de recebíveis","Reduzir o índice de chargebacks indevidos"]'::jsonb, '[{"label":"Tempo de ativação da maquininha","target":"< 10 min"},{"label":"Adesão à antecipação automática","target":"+15% no semestre"},{"label":"Índice de chargebacks indevidos","target":"< 0.3%"}]'::jsonb, '["C","Java","Spring Boot","RabbitMQ","MySQL"]'::jsonb, '{"lead":"Bruno Salgado","size":9,"squads":["Hardware","Recebíveis"]}'::jsonb, '["Conhecer o produto","Instalar ambiente","Configurar acessos","Ler documentação","Assistir vídeos","Realizar treinamento","Fazer exercício prático","Validar conhecimentos"]'::jsonb)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tagline = EXCLUDED.tagline, icon = EXCLUDED.icon, color = EXCLUDED.color, soft = EXCLUDED.soft, description = EXCLUDED.description, objectives = EXCLUDED.objectives, metrics = EXCLUDED.metrics, tech = EXCLUDED.tech, team = EXCLUDED.team, trilha = EXCLUDED.trilha, updated_at = now();

INSERT INTO public.project_contacts (project_id, name, role, contact, sort_order) VALUES ('tupi', 'Bruno Salgado', 'Tech Lead', 'bruno.salgado@empresa.com', 0);
INSERT INTO public.project_contacts (project_id, name, role, contact, sort_order) VALUES ('tupi', 'Heloísa Drumond', 'Product Manager', 'heloisa.drumond@empresa.com', 1);
INSERT INTO public.project_links (project_id, label, url, sort_order) VALUES ('tupi', 'Repositório principal', '#', 0);
INSERT INTO public.project_links (project_id, label, url, sort_order) VALUES ('tupi', 'Board do projeto', '#', 1);
INSERT INTO public.project_people (project_id, name, role, area, contact, specialty, sort_order) VALUES ('tupi', 'Bruno Salgado', 'Tech Lead', 'Engenharia', 'bruno.salgado@empresa.com', 'Sistemas embarcados', 0);
INSERT INTO public.project_people (project_id, name, role, area, contact, specialty, sort_order) VALUES ('tupi', 'Heloísa Drumond', 'Product Manager', 'Produto', 'heloisa.drumond@empresa.com', 'Recebíveis', 1);
INSERT INTO public.project_people (project_id, name, role, area, contact, specialty, sort_order) VALUES ('tupi', 'Tiago Murano', 'Engenheiro de Software', 'Engenharia', 'tiago.murano@empresa.com', 'Backend de pagamentos', 2);
INSERT INTO public.project_stakeholders (project_id, name, role, area, contact, influence, interest, expectativa, sort_order) VALUES ('tupi', 'Juliana Freitas', 'Gerente Comercial', 'Comercial', 'juliana.freitas@empresa.com', 'Alto', 'Alto', 'Crescimento de base de lojistas ativos', 0);
INSERT INTO public.project_stakeholders (project_id, name, role, area, contact, influence, interest, expectativa, sort_order) VALUES ('tupi', 'Marcos Vaz', 'Head de Operações', 'Operações', 'marcos.vaz@empresa.com', 'Alto', 'Médio', 'Redução de chamados de suporte de ativação', 1);
INSERT INTO public.project_stakeholders (project_id, name, role, area, contact, influence, interest, expectativa, sort_order) VALUES ('tupi', 'Sandra Oliveira', 'Diretora Financeira', 'Financeiro', 'sandra.oliveira@empresa.com', 'Médio', 'Alto', 'Controle das taxas e margens de antecipação', 2);
INSERT INTO public.project_meetings (project_id, name, frequency, duration, meeting_time, participants, descricao, link, sort_order) VALUES ('tupi', 'Daily', 'Diária', '15 min', '09:30', '["Devs","QA","Tech Lead"]'::jsonb, 'Alinhamento rápido do time sobre progresso e bloqueios.', 'https://meet.google.com/abc-defg-hij', 0);
INSERT INTO public.project_meetings (project_id, name, frequency, duration, meeting_time, participants, descricao, link, sort_order) VALUES ('tupi', 'Sprint Planning', 'A cada 2 semanas', '1h30', '10:00 (seg)', '["Devs","PO","Tech Lead"]'::jsonb, 'Planejamento do sprint com foco em hardware e recebíveis.', 'https://meet.google.com/abc-defg-hij', 1);
INSERT INTO public.project_meetings (project_id, name, frequency, duration, meeting_time, participants, descricao, link, sort_order) VALUES ('tupi', 'Sprint Review', 'A cada 2 semanas', '1h', '15:00 (sex)', '["Devs","PO","Comercial"]'::jsonb, 'Demonstração de funcionalidades entregues.', 'https://meet.google.com/abc-defg-hij', 2);
INSERT INTO public.project_meetings (project_id, name, frequency, duration, meeting_time, participants, descricao, link, sort_order) VALUES ('tupi', 'Retrospectiva', 'A cada 2 semanas', '45 min', '16:00 (sex)', '["Time completo"]'::jsonb, 'Avaliação do processo e definição de melhorias.', 'https://meet.google.com/abc-defg-hij', 3);
INSERT INTO public.project_meetings (project_id, name, frequency, duration, meeting_time, participants, descricao, link, sort_order) VALUES ('tupi', 'Sync Hardware', 'Semanal', '30 min', '14:00 (ter)', '["Squad Hardware"]'::jsonb, 'Alinhamento específico sobre firmware e comunicação POS.', 'https://meet.google.com/abc-defg-hij', 4);
INSERT INTO public.project_glossary (project_id, term, definition, sort_order) VALUES ('tupi', 'EMV', 'Padrão técnico de segurança usado em cartões com chip.', 0);
INSERT INTO public.project_glossary (project_id, term, definition, sort_order) VALUES ('tupi', 'Settlement', 'Liquidação financeira final de uma transação entre as partes.', 1);
INSERT INTO public.project_glossary (project_id, term, definition, sort_order) VALUES ('tupi', 'Chargeback', 'Estorno de uma transação contestada pelo titular do cartão.', 2);
INSERT INTO public.project_glossary (project_id, term, definition, sort_order) VALUES ('tupi', 'Antecipação', 'Recebimento adiantado de valores de vendas parceladas, mediante taxa.', 3);
INSERT INTO public.project_faq (project_id, category, question, answer, sort_order) VALUES ('tupi', 'Hardware', 'Como solicito uma maquininha de teste?', 'Solicite via canal #hardware-tupi informando o squad e o motivo.', 0);
INSERT INTO public.project_documents (project_id, category, title, doc_type, author, doc_date, url, sort_order) VALUES ('tupi', 'Arquitetura', 'Comunicação maquininha ↔ backend', 'Diagrama', 'Bruno Salgado', '2025-02-10'::date, '#', 0);
INSERT INTO public.project_documents (project_id, category, title, doc_type, author, doc_date, url, sort_order) VALUES ('tupi', 'Regras de negócio', 'Taxas e planos de antecipação', 'Documento', 'Heloísa Drumond', '2025-03-15'::date, '#', 1);
INSERT INTO public.project_documents (project_id, category, title, doc_type, author, doc_date, url, sort_order) VALUES ('tupi', 'Fluxos', 'Fluxo de ativação de maquininha', 'Fluxo', 'Bruno Salgado', '2025-04-22'::date, '#', 2);
INSERT INTO public.project_documents (project_id, category, title, doc_type, author, doc_date, url, sort_order) VALUES ('tupi', 'APIs', 'API de recebíveis', 'Referência', 'Tiago Murano', '2025-05-08'::date, '#', 3);
INSERT INTO public.project_documents (project_id, category, title, doc_type, author, doc_date, url, sort_order) VALUES ('tupi', 'Banco de Dados', 'Modelo de transações POS', 'Documento', 'Bruno Salgado', '2025-06-20'::date, '#', 4);
INSERT INTO public.project_documents (project_id, category, title, doc_type, author, doc_date, url, sort_order) VALUES ('tupi', 'Padrões de Código', 'Guia de estilo Java', 'Guia', 'Tiago Murano', '2025-07-05'::date, '#', 5);
INSERT INTO public.project_operation_alerts (project_id, nome, severidade, significado, acao, sort_order) VALUES ('tupi', 'POS_OFFLINE', 'Alta', 'Maquininha sem comunicação por mais de 10 minutos. Possível falha de rede no lojista ou travamento do firmware.', 'Verificar status no portal de gestão de dispositivos e acionar suporte remoto.', 0);
INSERT INTO public.project_operation_alerts (project_id, nome, severidade, significado, acao, sort_order) VALUES ('tupi', 'TRANSACTION_TIMEOUT', 'Alta', 'Transação sem resposta da adquirente em mais de 30s. Pode indicar instabilidade no gateway.', 'Checar status da adquirente e logs do serviço payment-gateway.', 1);
INSERT INTO public.project_operation_alerts (project_id, nome, severidade, significado, acao, sort_order) VALUES ('tupi', 'ANTECIPACAO_FALHA', 'Média', 'Falha na liquidação de antecipação de recebíveis.', 'Acionar squad de Recebíveis via #squad-recebiveis e verificar API do banco parceiro.', 2);
INSERT INTO public.project_operation_diagnostics (project_id, step_text, sort_order) VALUES ('tupi', '1. Verificar painel de status dos dispositivos POS no portal interno', 0);
INSERT INTO public.project_operation_diagnostics (project_id, step_text, sort_order) VALUES ('tupi', '2. Checar logs de transação no Kibana filtrando por terminal_id e status:failed', 1);
INSERT INTO public.project_operation_diagnostics (project_id, step_text, sort_order) VALUES ('tupi', '3. Confirmar se a falha é pontual (1 terminal) ou sistêmica (múltiplos terminais)', 2);
INSERT INTO public.project_operation_diagnostics (project_id, step_text, sort_order) VALUES ('tupi', '4. Verificar conectividade da adquirente nos dashboards de parceiros', 3);
INSERT INTO public.project_operation_diagnostics (project_id, step_text, sort_order) VALUES ('tupi', '5. Acionar o suporte remoto do hardware se o dispositivo não responder', 4);
INSERT INTO public.project_operation_diagnostics (project_id, step_text, sort_order) VALUES ('tupi', '6. Abrir ticket no sistema de suporte com evidências de logs para escalation', 5);
INSERT INTO public.project_operation_contacts (project_id, problema, responsavel, canal, sort_order) VALUES ('tupi', 'Falha de hardware / firmware', 'Bruno Salgado (Tech Lead)', '#hardware-tupi', 0);
INSERT INTO public.project_operation_contacts (project_id, problema, responsavel, canal, sort_order) VALUES ('tupi', 'Transação reprovada / gateway', 'Tiago Murano (Backend)', '#squad-pagamentos-tupi', 1);
INSERT INTO public.project_operation_contacts (project_id, problema, responsavel, canal, sort_order) VALUES ('tupi', 'Antecipação de recebíveis', 'Squad Recebíveis', '#squad-recebiveis', 2);
INSERT INTO public.project_operation_contacts (project_id, problema, responsavel, canal, sort_order) VALUES ('tupi', 'Atendimento ao lojista', 'Suporte Tupi', '#suporte-tupi', 3);
INSERT INTO public.project_operation_logs (project_id, sistema, onde, filtro, sort_order) VALUES ('tupi', 'Transações POS', 'Kibana → Index tupi-transactions', 'terminal_id:<id> AND status:failed | últimas 2h', 0);
INSERT INTO public.project_operation_logs (project_id, sistema, onde, filtro, sort_order) VALUES ('tupi', 'Firmware de dispositivos', 'Portal de gestão de dispositivos → Logs', 'Filtrar por device_id e nível WARN/ERROR', 1);
INSERT INTO public.project_operation_logs (project_id, sistema, onde, filtro, sort_order) VALUES ('tupi', 'API de recebíveis', 'Datadog → Services → recebiveis-api', 'status:error @operation:liquidacao', 2);
INSERT INTO public.project_operation_channels (project_id, nome, plataforma, descricao, sort_order) VALUES ('tupi', '#tupi-geral', 'Slack', 'Comunicações gerais do produto Tupi.', 0);
INSERT INTO public.project_operation_channels (project_id, nome, plataforma, descricao, sort_order) VALUES ('tupi', '#hardware-tupi', 'Slack', 'Discussões técnicas sobre dispositivos POS e firmware.', 1);
INSERT INTO public.project_operation_channels (project_id, nome, plataforma, descricao, sort_order) VALUES ('tupi', '#squad-recebiveis', 'Slack', 'Time responsável por antecipações e liquidações.', 2);
INSERT INTO public.project_operation_channels (project_id, nome, plataforma, descricao, sort_order) VALUES ('tupi', 'Board Jira Tupi', 'Jira', 'Backlog, sprints e épicos do produto Tupi.', 3);

