-- Projeto:  Convem Board
INSERT INTO public.projects (id, name, tagline, icon, color, soft, description, objectives, metrics, tech, team, trilha)
VALUES ('convem-board', 'Convem Board', 'Painel de gestão para lojistas parceiros', 'bar-chart', '#B45309', '#FDF1E3', 'Dashboard web onde lojistas acompanham vendas, conciliação financeira e relacionamento com a operação, centralizando os principais indicadores do negócio.', '["Reduzir chamados de suporte sobre conciliação em 30%","Aumentar o uso de relatórios exportáveis","Padronizar indicadores entre todos os segmentos de lojista"]'::jsonb, '[{"label":"Chamados de suporte sobre conciliação","target":"-30%"},{"label":"Uso de relatórios exportáveis","target":"+25% ao mês"},{"label":"Tempo de atualização dos indicadores","target":"≤ 1 hora"}]'::jsonb, '["React","TypeScript","Node.js","GraphQL","PostgreSQL"]'::jsonb, '{"lead":"Patrícia Anjos","size":7,"squads":["Indicadores","Conciliação"]}'::jsonb, '["Conhecer o produto","Instalar ambiente","Configurar acessos","Ler documentação","Assistir vídeos","Realizar treinamento","Fazer exercício prático","Validar conhecimentos"]'::jsonb)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, tagline = EXCLUDED.tagline, icon = EXCLUDED.icon, color = EXCLUDED.color, soft = EXCLUDED.soft, description = EXCLUDED.description, objectives = EXCLUDED.objectives, metrics = EXCLUDED.metrics, tech = EXCLUDED.tech, team = EXCLUDED.team, trilha = EXCLUDED.trilha, updated_at = now();

INSERT INTO public.project_contacts (project_id, name, role, contact, sort_order) VALUES ('convem-board', 'Patrícia Anjos', 'Tech Lead', 'patricia.anjos@empresa.com', 0);
INSERT INTO public.project_contacts (project_id, name, role, contact, sort_order) VALUES ('convem-board', 'Davi Mourão', 'Product Manager', 'davi.mourao@empresa.com', 1);
INSERT INTO public.project_links (project_id, label, url, sort_order) VALUES ('convem-board', 'Repositório principal', '#', 0);
INSERT INTO public.project_links (project_id, label, url, sort_order) VALUES ('convem-board', 'Board do projeto', '#', 1);
INSERT INTO public.project_people (project_id, name, role, area, contact, specialty, sort_order) VALUES ('convem-board', 'Patrícia Anjos', 'Tech Lead', 'Engenharia', 'patricia.anjos@empresa.com', 'Frontend de dados', 0);
INSERT INTO public.project_people (project_id, name, role, area, contact, specialty, sort_order) VALUES ('convem-board', 'Davi Mourão', 'Product Manager', 'Produto', 'davi.mourao@empresa.com', 'Experiência do lojista', 1);
INSERT INTO public.project_stakeholders (project_id, name, role, area, contact, influence, interest, expectativa, sort_order) VALUES ('convem-board', 'Thiago Corrêa', 'Head de Lojistas', 'Comercial', 'thiago.correa@empresa.com', 'Alto', 'Alto', 'Painel intuitivo que reduza chamados de suporte', 0);
INSERT INTO public.project_stakeholders (project_id, name, role, area, contact, influence, interest, expectativa, sort_order) VALUES ('convem-board', 'Priscila Neves', 'Gerente de Conciliação', 'Financeiro', 'priscila.neves@empresa.com', 'Médio', 'Alto', 'Conciliação automática e sem divergências', 1);
INSERT INTO public.project_stakeholders (project_id, name, role, area, contact, influence, interest, expectativa, sort_order) VALUES ('convem-board', 'Eduardo Rocha', 'Head de BI', 'Dados', 'eduardo.rocha@empresa.com', 'Médio', 'Médio', 'Padronização de métricas entre segmentos', 2);
INSERT INTO public.project_meetings (project_id, name, frequency, duration, meeting_time, participants, descricao, link, sort_order) VALUES ('convem-board', 'Daily', 'Diária', '15 min', '09:00', '["Devs","PO","Tech Lead"]'::jsonb, 'Alinhamento diário de andamento das tasks e bloqueios.', 'https://meet.google.com/abc-defg-hij', 0);
INSERT INTO public.project_meetings (project_id, name, frequency, duration, meeting_time, participants, descricao, link, sort_order) VALUES ('convem-board', 'Sprint Planning', 'A cada 2 semanas', '1h30', '10:00 (seg)', '["Devs","PO","Tech Lead"]'::jsonb, 'Definição das entregas do próximo sprint.', 'https://meet.google.com/abc-defg-hij', 1);
INSERT INTO public.project_meetings (project_id, name, frequency, duration, meeting_time, participants, descricao, link, sort_order) VALUES ('convem-board', 'Sprint Review', 'A cada 2 semanas', '1h', '15:00 (sex)', '["Devs","PO","Head de Lojistas"]'::jsonb, 'Apresentação das entregas do sprint para stakeholders.', 'https://meet.google.com/abc-defg-hij', 2);
INSERT INTO public.project_meetings (project_id, name, frequency, duration, meeting_time, participants, descricao, link, sort_order) VALUES ('convem-board', 'Retrospectiva', 'A cada 2 semanas', '1h', '16:00 (sex)', '["Time completo"]'::jsonb, 'Melhoria contínua do processo do time.', 'https://meet.google.com/abc-defg-hij', 3);
INSERT INTO public.project_meetings (project_id, name, frequency, duration, meeting_time, participants, descricao, link, sort_order) VALUES ('convem-board', 'Sync BI / Dados', 'Quinzenal', '45 min', '14:00 (qua)', '["Dev","Head BI"]'::jsonb, 'Alinhamento de métricas e indicadores com o time de dados.', 'https://meet.google.com/abc-defg-hij', 4);
INSERT INTO public.project_glossary (project_id, term, definition, sort_order) VALUES ('convem-board', 'Settlement', 'Liquidação financeira final de uma transação entre as partes.', 0);
INSERT INTO public.project_glossary (project_id, term, definition, sort_order) VALUES ('convem-board', 'Webhook', 'Notificação automática enviada por um sistema quando um evento ocorre.', 1);
INSERT INTO public.project_glossary (project_id, term, definition, sort_order) VALUES ('convem-board', 'API', 'Interface que permite a comunicação entre sistemas diferentes.', 2);
INSERT INTO public.project_faq (project_id, category, question, answer, sort_order) VALUES ('convem-board', 'Indicadores', 'Com que frequência os dados são atualizados?', 'Os indicadores são recalculados a cada hora.', 0);
INSERT INTO public.project_documents (project_id, category, title, doc_type, author, doc_date, url, sort_order) VALUES ('convem-board', 'Arquitetura', 'Visão geral do painel web', 'Diagrama', 'Patrícia Anjos', '2025-01-14'::date, '#', 0);
INSERT INTO public.project_documents (project_id, category, title, doc_type, author, doc_date, url, sort_order) VALUES ('convem-board', 'Regras de negócio', 'Regras de conciliação financeira', 'Documento', 'Davi Mourão', '2025-02-28'::date, '#', 1);
INSERT INTO public.project_documents (project_id, category, title, doc_type, author, doc_date, url, sort_order) VALUES ('convem-board', 'Design System', 'Componentes web compartilhados', 'Referência', 'Patrícia Anjos', '2025-03-10'::date, '#', 2);
INSERT INTO public.project_documents (project_id, category, title, doc_type, author, doc_date, url, sort_order) VALUES ('convem-board', 'APIs', 'Schema GraphQL', 'Referência', 'Patrícia Anjos', '2025-04-25'::date, '#', 3);
INSERT INTO public.project_documents (project_id, category, title, doc_type, author, doc_date, url, sort_order) VALUES ('convem-board', 'Boas práticas', 'Checklist de acessibilidade', 'Guia', 'Davi Mourão', '2025-06-12'::date, '#', 4);
INSERT INTO public.project_operation_alerts (project_id, nome, severidade, significado, acao, sort_order) VALUES ('convem-board', 'CONCILIACAO_DIVERGENCIA', 'Alta', 'Divergência detectada entre vendas registradas e repasses efetivados acima de R$ 1.000.', 'Acionar squad de Conciliação via #conciliacao-convem com o relatório de divergência.', 0);
INSERT INTO public.project_operation_alerts (project_id, nome, severidade, significado, acao, sort_order) VALUES ('convem-board', 'DASHBOARD_DATA_STALE', 'Média', 'Dados do painel com mais de 2h sem atualização. Possível falha no pipeline de dados.', 'Verificar jobs do Airflow e logs do serviço de ingestão de dados.', 1);
INSERT INTO public.project_operation_alerts (project_id, nome, severidade, significado, acao, sort_order) VALUES ('convem-board', 'EXPORT_FAILURE', 'Baixa', 'Falha na geração de relatório exportável pelo lojista.', 'Verificar logs do serviço report-generator e queue de jobs de exportação.', 2);
INSERT INTO public.project_operation_diagnostics (project_id, step_text, sort_order) VALUES ('convem-board', '1. Verificar o status dos jobs de conciliação no painel do Airflow', 0);
INSERT INTO public.project_operation_diagnostics (project_id, step_text, sort_order) VALUES ('convem-board', '2. Checar logs do serviço de ingestão de dados no Datadog', 1);
INSERT INTO public.project_operation_diagnostics (project_id, step_text, sort_order) VALUES ('convem-board', '3. Confirmar se a divergência afeta um único lojista ou é sistêmica', 2);
INSERT INTO public.project_operation_diagnostics (project_id, step_text, sort_order) VALUES ('convem-board', '4. Verificar a integridade dos dados no banco PostgreSQL', 3);
INSERT INTO public.project_operation_diagnostics (project_id, step_text, sort_order) VALUES ('convem-board', '5. Acionar o time de dados se o pipeline estiver com lag', 4);
INSERT INTO public.project_operation_diagnostics (project_id, step_text, sort_order) VALUES ('convem-board', '6. Abrir ticket de suporte com CNPJ do lojista afetado para rastreamento', 5);
INSERT INTO public.project_operation_contacts (project_id, problema, responsavel, canal, sort_order) VALUES ('convem-board', 'Divergência de conciliação', 'Priscila Neves + Squad Conciliação', '#conciliacao-convem', 0);
INSERT INTO public.project_operation_contacts (project_id, problema, responsavel, canal, sort_order) VALUES ('convem-board', 'Dados desatualizados no painel', 'Patrícia Anjos (Tech Lead)', '#convem-board-dev', 1);
INSERT INTO public.project_operation_contacts (project_id, problema, responsavel, canal, sort_order) VALUES ('convem-board', 'Falha em exportação de relatório', 'Squad Indicadores', '#squad-indicadores', 2);
INSERT INTO public.project_operation_contacts (project_id, problema, responsavel, canal, sort_order) VALUES ('convem-board', 'Problemas de acesso do lojista', 'Suporte Convem', '#suporte-convem', 3);
INSERT INTO public.project_operation_logs (project_id, sistema, onde, filtro, sort_order) VALUES ('convem-board', 'Pipeline de dados (Airflow)', 'Airflow UI → DAGs → convem_ingestion', 'Status failed/upstream_failed nas últimas 6h', 0);
INSERT INTO public.project_operation_logs (project_id, sistema, onde, filtro, sort_order) VALUES ('convem-board', 'API do painel', 'Datadog → Services → convem-board-api', 'status:error @endpoint:/api/indicadores', 1);
INSERT INTO public.project_operation_logs (project_id, sistema, onde, filtro, sort_order) VALUES ('convem-board', 'Serviço de exportação', 'Datadog Logs → Index production', 'service:report-generator level:ERROR', 2);
INSERT INTO public.project_operation_channels (project_id, nome, plataforma, descricao, sort_order) VALUES ('convem-board', '#convem-board-geral', 'Slack', 'Canal principal do time Convem Board.', 0);
INSERT INTO public.project_operation_channels (project_id, nome, plataforma, descricao, sort_order) VALUES ('convem-board', '#conciliacao-convem', 'Slack', 'Discussões sobre conciliação financeira e divergências.', 1);
INSERT INTO public.project_operation_channels (project_id, nome, plataforma, descricao, sort_order) VALUES ('convem-board', '#squad-indicadores', 'Slack', 'Time de indicadores e BI.', 2);
INSERT INTO public.project_operation_channels (project_id, nome, plataforma, descricao, sort_order) VALUES ('convem-board', 'Board Jira Convem', 'Jira', 'Gestão de tarefas e sprints do produto.', 3);

